project:
  type: book

book:
  title: "Simple Notes"
  author: "mv"
  date: "28/01/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - introduction.qmd
    - time.qmd
    - circularpath.qmd
    - motion.qmd
    - symmetry.qmd
    - frequency.qmd
    - waves.qmd
    - signals.qmd
    - fourieranalysis.qmd
    - transforms.qmd
    - reversetransforms.qmd
    - exercises.qmd
    - implementations.qmd
    - project.qmd
    - applications.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



