# Motion

On what ground are the Fourier tools laid upon? The answer depends, of the desired output. As an introductory and naive approach, it seemed relevant to seek technical definitions, and understand the underlaying concepts of such core ideas. Sir Isaac Newton, in Philosophiæ Naturalis Principia Mathematica, based his description of planetary motions, introducion the notion of a medium allowing this particular set of dynamic interaction. 
%In his aether model, Newton describes aether as a medium that "flows" continually downward toward the Earth's surface and is partially absorbed and partially diffused. This "circulation" of aether is what he associated the force of gravity with to help explain the action of gravity in a non-mechanical fashion.
 Kepler had a mystical belief that the circle was the Universe’s perfect shape, and that as a manifestation of Divine order, the planets’ orbits must be circular. For many years, he struggled to make Brahe’s observations of the motions of Mars match up with a circular orbit.

Eventually, however, Kepler noticed that an imaginary line drawn from a planet to the Sun swept out an equal area of space in equal times, regardless of where the planet was in its orbit. If you draw a triangle out from the Sun to a planet’s position at one point in time and its position at a fixed time later—say, 5 hours, or 2 days—the area of that triangle is always the same, anywhere in the orbit. For all these triangles to have the same area, the planet must move more quickly when it is near the Sun, but more slowly when it is farthest from the Sun.

This discovery (which became Kepler’s second law of orbital motion) led to the realization of what became Kepler’s first law: that the planets move in an ellipse (a squashed circle) with the Sun at one focus point, offset from the center.

 By unifying all motion, Newton shifted the scientific perspective to a search for large, unifying patterns in nature. Newton outlined his laws in Philosophiae Naturalis Principia Mathematica (“Mathematical Principles of Natural Philosophy,”) published in 1687.

Law I. Every body perseveres in its state of rest, or of uniform motion in a right line, unless it is compelled to change that state by forces impressed theron.

In essence, a moving object won’t change speed or direction, nor will a still object start moving, unless some outside force acts on it. The law is regularly summed up in one word: inertia.

Law II. The alteration of motion is ever proportional to the motive force impressed; and is made in the direction of the right line in which that force is impressed.

Newton’s second law is most recognizable in its mathematical form, the iconic equation: F=ma. The strength of the force (F) is defined by how much it changes the motion (acceleration, a) of an object with some mass (m).

Law III. To every action there is always opposed an equal reaction: or the mutual actions of two bodies upon each other are always equal, and directed to contrary parts.

As Newton himself described: “If you press a stone with your finger, the finger is also pressed by the stone.”



![Isaac Newton demonstrated his universal law of gravitation by showing that a comet visible during 1680 and 1681 followed the path of a parabola. [Adapted from Isaac Newton, 1687. Philosophiae Naturalis Principia Mathematica (“Mathematical Principles of Natural Philosophy.”)]](https://earthobservatory.nasa.gov/ContentFeature/OrbitsHistory/images/newton_comet_orbit.png)


Einstein and Relativity
The ideas outlined in Newton’s laws of motion and universal gravitation stood unchallenged for nearly 220 years until Albert Einstein presented his theory of special relativity in 1905. Newton’s theory depended on the assumption that mass, time, and distance are constant regardless of where you measure them.

The theory of relativity treats time, space, and mass as fluid things, defined by an observer’s frame of reference. All of us moving through the universe on the Earth are in a single frame of reference, but an astronaut in a fast-moving spaceship would be in a different reference frame.

